#!/bin/bash
echo "Making a new directory ~/mywifidrivers/";
mkdir ~/mywifidrivers;
cd ~/mywifidrivers;
echo "cloning git repo...";
git clone https://github.com/lwfinger/rtlwifi_new.git;
echo "Entering ~/mywifidrivers/rtlwifi_new...";
cd ~/mywifidrivers/rtlwifi_new/;
make;
sudo make install;
echo "removing module 'rtl8723be' ...";
sudo modprobe -rv rtl8723be;
echo "adding module 'rtl8723be'...";
sudo modprobe -v rtl8723be ips=0 ant_sel=2;