#!/bin/bash

#############################################################################
# Run this script ((after kernel update)) to automatically update rtl8723be #
# drivers from github.com/lwfinger/rtlwifi_new. He is our saviour.          #
# TO USE:-																	#		
# **AVOID STEP 1 IF YOU ALREADY HAVE THE FILES**							#
#																			#
# 1) clone lwfinger's repo to ~/mywifidrivers/								#
#			mkdir /home/$USER/mywifidrivers/								#
#			cd /home/$USER/mywifidrivers/									#		
#			git clone https://github.com/lwfinger/rtlwifi_new				#
# 2) Give this script permissions:- 										#	
# 			sudo chmod 744 wifi-fix											#
# 3) Run this script using source or . (DO NOT RUN THIS SCRIPT WITH SUDO)	#
#			. ./wifi-fix "OR" source ./wifi-fix								#						
#			(Provide with password only when asked for)						#	
# 4) Restart your system:-													#
#			sudo reboot														#		
#																			#
# Author: github.com/mrinalabrol											#	
#############################################################################


echo "\nEntering ~/mywifidrivers/rtlwifi_new..."
cd ~/mywifidrivers/rtlwifi_new/
echo "\nChanging branch to rock.new_btcoex..."
git checkout rock.new_btcoex
git_branch="`git rev-parse --abbrev-ref HEAD`"
test_branch="rock.new_btcoex"
if [ $git_branch = $test_branch ]; then
	make
	sudo make install
	echo "\nremoving module 'rtl8723be' ..."
	sudo modprobe -rv rtl8723be
	echo "\nadding module 'rtl8723be'..."
	sudo modprobe -v rtl8723be ips=0 ant_sel=2
else
	echo "Not in correct branch, aborting...\n"
	return -1
fi
